import { test, expect } from "./fixtures.mjs";

test.use({ packaged: true });

test("installed bundle supports search, saved settings and exact row writes in a real browser", async ({ page, canvas }) => {
  for (const row of canvas.rows) row.reason = "subscribed";
  canvas.rows[1].reason = "review_requested";
  await page.setViewportSize({ width: 320, height: 800 });
  await page.goto(canvas.url);
  await expect(page.locator(".row")).toHaveCount(50);
  await expect(page.locator(".metadata").getByText("Unread", { exact: true })).toHaveCount(0);
  await expect(page.locator(".eyebrow")).toBeVisible();
  await expect(page.locator("#subtitle")).toBeVisible();
  await expect(page.getByRole("searchbox")).toHaveAttribute("placeholder", "Search...");
  await expect(page.getByRole("button", { name: "Mark 1 shown, loaded notifications as read in example/tools", exact: true })).toHaveCount(0);
  const next = page.getByRole("button", { name: "Scroll attention tabs right", exact: true });
  await expect(next).toBeVisible();
  await next.click();
  await expect.poll(() => page.locator("#attention-tabs").evaluate(node => node.scrollLeft)).toBeGreaterThan(0);
  await expect(page.getByRole("tab", { name: "All (50)", exact: true })).toHaveAttribute("aria-selected", "true");
  await page.setViewportSize({ width: 960, height: 720 });
  await expect(next).toBeHidden();
  await expect(page.locator("#development-build")).toBeHidden();
  await expect(page.locator("#development-build")).toBeEmpty();
  await expect(page.locator("footer")).toBeHidden();
  await expect(page.locator(".toolbar > #refresh-control + #settings")).toHaveCount(1);
  await page.getByRole("searchbox").fill("Needle");
  await expect(page.locator(".row")).toHaveCount(3);
  await page.getByRole("tab", { name: "Review requested (1)", exact: true }).click();
  await expect(page.locator(".row")).toHaveCount(1);
  await page.getByLabel("Settings", { exact: true }).click();
  await page.getByRole("combobox", { name: "Theme", exact: true }).selectOption("dark");
  await expect(page.locator("html")).toHaveAttribute("data-notification-theme", "dark");
  await page.getByRole("combobox", { name: "Group By", exact: true }).selectOption("none");
  await expect(page.locator(".repo-group")).toHaveCount(0);
  await page.keyboard.press("Escape");
  await page.getByRole("button", { name: "Mark as read: Needle widget 2", exact: true }).click();
  await expect(page.locator(".row")).toHaveCount(0);
  await expect(page.locator("#empty-title")).toHaveText("No matches in loaded notifications");
  await page.getByRole("searchbox").fill("");
  await expect(page.getByRole("searchbox")).toHaveValue("");
  await expect(page.getByRole("tab", { name: "Review requested (0)", exact: true })).toHaveAttribute("aria-selected", "true");
  await expect(page.locator(".row")).toHaveCount(0);
  await page.getByRole("tab", { name: "All (49)", exact: true }).click();
  await expect(page.locator(".row")).toHaveCount(49);
  expect(canvas.writes).toEqual(["2"]);
  await page.reload();
  await expect(page.locator("html")).toHaveAttribute("data-notification-theme", "dark");
  await expect(page.locator(".repo-group")).toHaveCount(0);
  expect((await canvas.preferences.read()).groupBy).toBe("none");
});
